# Generated by Django 6.0.5 on 2026-06-03 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
