# Generated by Django 6.0.5 on 2026-06-04 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0002_prescription_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='dosage',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='prescription',
            name='medicine',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='prescription',
            name='patient_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
