# Generated by Django 6.0.5 on 2026-10-07 13:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_doctor_user'),
        ('prescription', '0003_prescription_dosage_prescription_medicine_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='additional_instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='prescription',
            name='diagnosis',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='home.booking'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='symptoms',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='prescriptions/'),
        ),
    ]
