# Generated by Django 6.0.6 on 2026-06-22 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='token_no',
            field=models.PositiveIntegerField(editable=False, null=True, unique=True),
        ),
    ]
